### ISSUE TITLE
Tutorial for example

### ISSUE THREAD

**Issue by siisee11** [MuhammedKpln/peerdart#10]
Is there any setup tutorial to run the example? like server setup, signaling, turn, stun,...

Should I use this one?
https://github.com/peers/peerjs-server

Thank you :)

**Comment by MuhammedKpln** [comment]
You can read PeerJS [documentation](https://peerjs.com/docs/#start) which will work just fine with PeerDart except the syntax. As for signaling you don't have to install any server, Just plug-in-play!

**Comment by siisee11** [comment]
Thanks for the reply!
