### ISSUE TITLE
Example registering listen even for data on the wrong object.

### ISSUE THREAD

**Issue by SamORichards** [MuhammedKpln/peerdart#12]
Hi there!

Really interested in this package and have been trying to use it for a simple example to try it out!

I have been trying to implement a basic data transfer. The example has the listen for the data event on the dataconnection object returned by the peer.connect("PEERS ID") method. However in the dataconnection.dart file in the _handleDataMessage method the event is emitted on the provider variable which is the Peer object, not the super (baseconnection) like the open event.  Not sure which is the correct behavior, either updating the docs and examples or changing to super. My first is it likely should be on the super (baseconnection) so we know where the data is specifically coming from, but, not sure if that is correct.

**Comment by MuhammedKpln** [comment]
Correct! sorry for the late answer.
