### ISSUE TITLE
i am getting this error when i am using your example

### ISSUE THREAD

**Issue by Basim2Shaban** [MuhammedKpln/peerdart#14]
E/flutter ( 4031): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String?'
E/flutter ( 4031): #0      new PeerConnectOption.fromMap (package:peerdart/src/option_interfaces.dart:107:18)
E/flutter ( 4031): #1      Peer._handleMessage (package:peerdart/src/peer.dart:220:59)
E/flutter ( 4031): #2      Peer._createServerConnection.<anonymous closure> (package:peerdart/src/peer.dart:121:7)
E/flutter ( 4031): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 4031): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 4031): #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4031): #6      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter ( 4031): #7      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter ( 4031): #8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 4031): #9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 4031): #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 4031): #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4031): #12     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
E/flutter ( 4031): #13     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
E/flutter ( 4031): #14     _WhereTypeStreamSink.add (package:rxdart/src/transformers/where_type.dart:11:19)
E/flutter ( 4031): #15     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
E/flutter ( 4031): #16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 4031): #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 4031): #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4031): #19     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter ( 4031): #20     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
E/flutter ( 4031): #21     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 4031): #22     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 4031): #23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 4031): #24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4031): #25     _SyncBroadcastStreamController._sendData.<anonymous closure> (dart:async/broadcast_stream_controller.dart:385:20)
E/flutter ( 4031): #26     _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:322:15)
E/flutter ( 4031): #27     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:384:5)
E/flutter ( 4031): #28     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
E/flutter ( 4031): #29     StreamEventEmitter.emitEvent (package:events_emitter/emitters/stream_event_emitter.dart:53:51)
E/flutter ( 4031): #30     StreamEventEmitter.emit (package:events_emitter/emitters/stream_event_emitter.dart:92:40)
E/flutter ( 4031): #31     Socket.start.<anonymous closure> (package:peerdart/src/socket.dart:54:7)
E/flutter ( 4031): #32     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 4031): #33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 4031): #34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4031): #35     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter ( 4031): #36     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253:10)
E/flutter ( 4031): #37     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 4031): #38     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 4031): #39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 4031): #40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4031): #41     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter ( 4031): #42     _StreamController._add (dart:async/stream_controller.dart:648:7)
E/flutter ( 4031): #43     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 4031): #44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 4031): #45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 4031): #46     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
E/flutter ( 4031): #47     _StreamController._add (da

**Comment by MuhammedKpln** [comment]
The example hasn't been updates yet to latest version, will update it as soon as i have time!

**Comment by MuhammedKpln** [comment]
Released new version (0.5.0), can you reproduce issue in version 0.5.0?

**Comment by Basim2Shaban** [comment]
thank you veeeeery much , it's working now
