### ISSUE TITLE
On data event no being emitted on the DataConnection object

### ISSUE THREAD

**Issue by SamORichards** [MuhammedKpln/peerdart#15]
Hi there,

Following along from the referenced peerJS documentation link it seems that you should be able to listen for an on data event on the DataConnection object given back to you when an on connection event is triggered. I don't seem to be able to get that to work though. When sending the message I seem to only get on data event when listening on the peer object.

I need it on the DataConnection so I can send a reply to the correct remote connection. Is this an issue or am I doing this incorrectly?

Thanks in advance!

```void main() {
  var peer = Peer();

  peer.once("open").asStream().listen((event) {
    connected = true;
    print("Connection established");
  });

 
  peer.on<DataConnection>("connection").listen((connection) {
    //Connection of remote peer
    connection.on("open").listen((event) {});

    connection.on("data").listen((event) {
      //This never runs
      print("inner loop");
    });

    // On peer closed.
    connection.on("close").listen((event) {});
  });

  peer.on("data").listen((data) {
    //This always runs
    print("Outer reader worked");
  });
}

**Comment by MuhammedKpln** [comment]
Are you using the beta version? 

Released new version (0.5.0), This issue is already fixed in #12.

**Comment by SamORichards** [comment]
Was using the 4.0 beta, will try 5.0 now, thanks!

**Comment by SamORichards** [comment]
That fixed it thanks!
