### ISSUE TITLE
the answer user can't get the stream from the caller user !!

### ISSUE THREAD

**Issue by Basim2Shaban** [MuhammedKpln/peerdart#17]
hello everyone i have this problem , the user who's  answer can't receive any stream from the caller user
.
.
. this is my code 
.
![image](https://user-images.githubusercontent.com/37590883/213340631-6b3b2969-bedc-43f8-bc66-d6d1bd94c1be.png)
.
.
.
![image](https://user-images.githubusercontent.com/37590883/213340683-3f4b2588-bf49-471c-8bb2-1b06f067c034.png)

**Comment by MuhammedKpln** [comment]
Does this still ocurs with latest(0.5.1) version?

**Comment by prabhuc94** [comment]
> Does this still ocurs with latest(0.5.1) version?

Yes!

**Comment by MuhammedKpln** [comment]
@prabhuc94 Can you please provide a reproducible example?, as it's kind a hard to see what goes wrong from the picture.

**Comment by prabhuc94** [comment]
> @prabhuc94 Can you please provide a reproducible example?, as it's kind a hard to see what goes wrong from the picture.

Actually within same network /wifi able to get the Sender and Receiver Stream, But Outside the network (A in Wifi B in Mobile) only the stream getting but not appearing in RTCVideoRenderer. I've waited almost 10mins no response! In Some cases IceConnectionState failed after mediaConnection.on('stream) triggered!.
If possible kindly share a new example which will work outside the network! this will help us, Thanks!

**Comment by MuhammedKpln** [comment]
Turns out we were using old turn servers from peerjs, please test it again with version 0.5.2.

**Comment by prabhuc94** [comment]
> Turns out we were using old turn servers from peerjs, please test it again with version 0.5.2.

Thanks!, Let me check and update here!

**Comment by prabhuc94** [comment]
> Turns out we were using old turn servers from peerjs, please test it again with version 0.5.2.

![image](https://github.com/MuhammedKpln/peerdart/assets/24710386/b93caad1-0873-4595-8f2b-6752278e7ab1)
Streams not listening!
