### ISSUE TITLE
Unhandled Exception: type 'String' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by abhijit-hota** [MuhammedKpln/peerdart#18]
**Describe the bug**
An unexpected exception on new Peer instantiation

I initialized the Peer instance with the following code:

```dart

Peer? connectPeer() {
  try {
    final peer = Peer(
      options: PeerOptions(
        secure: true,
        host: baseURL.replaceAll("https://", ""),
        path: "/peer/peer",
        debug: LogLevel.All,
      ),
    );
    return peer;
  } catch (e) {
    return null;
  }
}
```

I receive the success messages as expected: 
```
I/flutter (25179): PeerDart:  Socket open
I/flutter (25179): PeerDart:  Server message received:{type: OPEN}
I/flutter (25179): PeerDart:  Server message received:Hello World!
```

Although, after that, I face this error:

```
E/flutter (25179): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'Map<String, dynamic>'
E/flutter (25179): #0      Socket.start.<anonymous closure>
```

**Smartphone (please complete the following information):**
 - Device: Samsung A30
 - OS: Android 12
 - Peerdart version: latest

**Comment by abhijit-hota** [comment]
Found the bug. The server was sending the string `"Hello World"`. But the emit event has a `Map<string, dynamic>` type param. IMO, it should be `dynamic` as strings are a valid message type.

**Comment by abhijit-hota** [comment]
Digging deeper, I found that, the `ServerMessage` class is restricted to use only limited `type`s and `payload`s. Is this intended? I hope documenting the types properly is in the roadmap.

**Comment by MuhammedKpln** [comment]
> Digging deeper, I found that, the `ServerMessage` class is restricted to use only limited `type`s and `payload`s. Is this intended? I hope documenting the types properly is in the roadmap.

Yes, it is intented. Peerjs is tightly restricted to working with their own backend. It's hard to guess what you will receive as payload when we don't have any documentation unfortunately.
