### ISSUE TITLE
Is it free / can I use it with multiple users

### ISSUE THREAD

**Issue by LamaAgent** [MuhammedKpln/peerdart#21]
I have two questions about this plugin: 
1. I would really like to use it, is it free?  And 2. Can I use it to connect multiple players?

**Comment by MuhammedKpln** [comment]
It is free, yes you can use it to connect multiple players as long as webrtc allows it.

**Comment by LamaAgent** [comment]
What do you mean by that? @MuhammedKpln

**Comment by LamaAgent** [comment]
How can I connect to multiple peers?

**Comment by LamaAgent** [comment]
Bump @MuhammedKpln
