### ISSUE TITLE
[Clarification]: Can we access audio received in UInt8List format?

### ISSUE THREAD

**Issue by TheSingletonDev** [MuhammedKpln/peerdart#26]
Hi Developer,
I wanted to check if it is possible to receive the byte stream of the audio. I want to get access to the audio received in the live call to send it to a speech recognition system which accepts raw PCM16 audio data. Is it possible, to somehow get access to the same while the live call is going on?

**Comment by MuhammedKpln** [comment]
You can try to use `captureFrame` method on stream event which is provided by the `flutter_webrtc`
