### ISSUE TITLE
Stream not receiving outside the network!

### ISSUE THREAD

**Issue by prabhuc94** [MuhammedKpln/peerdart#28]
Exception: Negotiation of connection to [PEERID] failed.

**Comment by prabhuc94** [comment]
![Screenshot 2023-07-24 at 11 38 17 AM](https://github.com/MuhammedKpln/peerdart/assets/24710386/291acce4-5cd5-44ff-a112-cee95d7cb4b6)

**Comment by MuhammedKpln** [comment]
I have disabled tests, will release a new minor version.
