### ISSUE TITLE
Uncaught (in promise) Error: Bad state: Cannot fire new event. Controller is already firing an event

### ISSUE THREAD

**Issue by Thaerith** [MuhammedKpln/peerdart#29]
Hello, have you already faced this exception ?
I checked your example within a cubit (as singleton) and extras to release webcam. 

**Describe the bug**

`Uncaught (in promise) Error: Bad state: Cannot fire new event. Controller is already firing an event`

**To Reproduce**
1. Make a first call (video stream in my case)
2. Close
3. Make a new call
4. exception is thrown

Best regards,

**Comment by MuhammedKpln** [comment]
Hello, i'm aware of this issue and will make new release that fixes this issue. As for now when closing a call it basically destroys the instance which throws a error later on. Quick workaround for this is creating new instance on destroy. 

Edit: You should close call with `dispose` method.
