### ISSUE TITLE
Example app doesn't work

### ISSUE THREAD

**Issue by JosephKalash** [MuhammedKpln/peerdart#33]
I'm trying to run example app on mobile it build and install successfully, but after share the peer id to the other device and try to connect it doesn't.
the error log:
` getUserMedia(): DOMException, NotAllowedError
E/flutter (30108): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to getUserMedia: getUserMedia(): DOMException, NotAllowedError
E/flutter (30108): #0      MediaDeviceNative.getUserMedia (package:flutter_webrtc/src/native/mediadevices_impl.dart:48:7)
E/flutter (30108): <asynchronous suspension>
E/flutter (30108): #1      _CallExampleState.connect (package:example/call_example.dart:65:25)
E/flutter (30108): <asynchronous suspension>`

I tried the web demo and for 2 separate devices it doesn't work also.

package version the latest 
Flutter version: 3.10

**Comment by MuhammedKpln** [comment]
Check your permissions, seems you've blocked permission to access your camera/microphone.
