### ISSUE TITLE
Compatible with PeerJS?

### ISSUE THREAD

**Issue by danielfvm** [MuhammedKpln/peerdart#36]
I've been trying to connect from a website with peerjs to peerdart. I both tried running peerdart on Linux and on my android phone. I see the connection is being established, but I am unable to send data between them (both directions) (connection is still open). 

I was wondering if peerdart is even compatible with peerjs, as it only claims to mirror the design of peerjs and not to be compatible with it?

I was using version 0.5.3.

**Comment by MuhammedKpln** [comment]
As for now, no it's not compatible. As peerjs now send all kind of data as binary.
