### ISSUE TITLE
Communication issue between Android and Web

### ISSUE THREAD

**Issue by Vovanella95** [MuhammedKpln/peerdart#42]
**Describe the bug**
Web app can sent only Binary messages to Android app

**To Reproduce**
1. Fix [#40](https://github.com/MuhammedKpln/peerdart/issues/40)
2. Run Flutter app on Android and Web
3. Connect Web to Android (try different networks)
4. Try to sent String message

**Expected behavior**
Message is received on Android device

**Actual behavior**
Only binary messages are received. String messages are not handled

**Devices:**
 - Chrome Web
 - Samsung Galaxy S20
 - Samsung Galaxy Tab 7

**Comment by MuhammedKpln** [comment]
The problem is that peerjs handles all messages from datachannel as an array buffer even when it's simple as string. As for now peerdart does not support it.

**Comment by Vovanella95** [comment]
Hi @MuhammedKpln , thanks for quick response. If it's not supported - feel free to close issue
