### ISSUE TITLE
How to handle client disconnection?

### ISSUE THREAD

**Issue by theniceboy** [MuhammedKpln/peerdart#5]
Hi, thank you for the fantastic package! I have a quick question regarding the client events. How do you handle client disconnection?

Thanks!
David

**Comment by MuhammedKpln** [comment]
Sorry for the late answer! Here is how you can listen when other peer disconnect.

```dart
peer.on("connection", null, (ev, _) => {
  final conn = event.eventData as DataConnection
  conn.on("close", null, (event, _) => {
  // Will print 'hi!'
  print("Peer disconnected");
  });
});
 ```

**Comment by theniceboy** [comment]
Thank you so much!!
