### ISSUE TITLE
I am building a omegle clone but i am not getting remote videos

### ISSUE THREAD

**Issue by Ayushpanditmoto** [MuhammedKpln/peerdart#8]
I have used 3 devices in order to test

![Screenshot_10](https://user-images.githubusercontent.com/31253617/197450467-7a567ea9-1235-46e0-b8f8-07f1ac7fe07b.png)
![Screenshot_11](https://user-images.githubusercontent.com/31253617/197450478-0a6932f0-032a-4104-aea8-533a377f6985.png)

**Comment by Ayushpanditmoto** [comment]
i am trying to write the code in this way can you help me

const socket = io.connect()
//"ws://localhost:5500"

let theUUID
let peerConnection
let localStream
let otherUser
let peerID
let otherPeerID

let form = document.getElementById('form')
let input = document.getElementById('input')
let theMessages = document.getElementById('messages')
let onlineCounter = document.querySelector('h3')

let joined = false
let waitingOnConnection = false
let videoOn

const myPeer = new Peer()

socket.on('oc', (oc) => {
  onlineCounter.innerHTML = 'Users online: ' + oc
})

form.addEventListener('submit', function (e) {
  e.preventDefault()
  if (input.value && joined) {
    //if not blank
    let msg = input.value
    socket.emit('message', msg)
    let item = document.createElement('li')
    item.innerHTML = "<h4 id='you'>You: </h4>" + msg
    messages.appendChild(item)
    input.value = '' //clear
    theMessages.scrollTo(0, theMessages.scrollHeight)
  } else if (waitingOnConnection) {
    serverMsg('Waiting for stranger')
  } else if (!joined) {
    serverMsg('You havent joined a Room yet! Please click "New Room"')
  } else {
    serverMsg('You cannot send a blank message.')
  }
})

socket.on('message', function (msg, servermsg) {
  if (servermsg) {
    serverMsg(msg)
  } else {
    strangerMsg(msg)
  }
})

myPeer.on('open', (id) => {
  peerID = id
})

socket.on('connect', () => {
  navigator.getUserMedia =
    navigator.getUserMedia ||
    navigator.mozGetUserMedia ||
    navigator.webkitGetUserMedia ||
    navigator.msGetUserMedia
  const constraints = {
    video: {
      width: {
        min: 480,
        max: 1280,
      },
      aspectRatio: 1.33333,
    },
    audio: true,
  }
  navigator.mediaDevices
    .getUserMedia(constraints)
    .then((stream) => {
      console.log('Got MediaStream:', stream)
      localStream = stream
      document.getElementById('local-video').srcObject = localStream
      if (!localStream.active) {
        videoOn = false
        console.log('No Video!')
        serverMsg(
          'Webcam not detected, please refresh page and make sure your webcam permission are correctly set! (Chrome works best)'
        )
        localStream = {}
        console.log('localStream: ' + localStream)
      } else {
        videoOn = true
        console.log('Video is on')
      }
    })
    .catch((error) => {
      console.error('Error accessing media devices.', error)
      videoOn = false
      console.log('No Video!')
      serverMsg(
        'Webcam not detected, please refresh page and make sure your webcam permission are correctly set! (Chrome works best)'
      )
    })
})

function joinRoom() {
  serverMsg('Searching for a stranger...')
  waitingOnConnection = true
  joined = false
  socket.emit('join room', peerID, videoOn)
  document.getElementById('remote-video').srcObject = undefined
  myPeer.on('call', (call) => {
    call.answer(localStream)

    call.on('stream', (theStream) => {
      document.getElementById('remote-video').srcObject = theStream
    })
  })
}

socket.on('user joined', (id, pid, vOn) => {
  //host
  otherPeerID = pid
  console.log('User connected: ' + id + ' ' + pid)
  socket.emit('send peerid', id, peerID)
  theMessages.innerHTML = ''
  try {
    connectToNewUser(pid, localStream)
  } catch (e) {
    console.log('Error connecting to User: ' + e)
    serverMsg(
      'Media connection not established due to your webcam having an issue, Chat only.'
    )
    socket.emit(
      'message',
      'Media connection not established due to stranger having a webcam error, He cannot see or hear you, Chat only.',
      true
    )
  }
  serverMsg('Connected to a stranger, say hi!')
  joined = true
  waitingOnConnection = false
  if (!vOn) {
    document.getElementById('vidoff').innerHTML = 'Stranger has no video'
  }
  otherUser = id //handshake
})
function connectToNewUser(pid, stream) {
  const call = myPeer.call(pid, stream)
  call.on('stream', (theStream) => {
    document.getElementById('remote-video').srcObject = theStream
  })
}
socket.on('other user', (ou, vOn) => {
  theMessages.innerHTML = ''
  console.log('you joined: ' + ou)
  joined = true
  waitingOnConnection = false
  serverMsg('Connected to a stranger, say hi!')
  if (!vOn) {
    document.getElementById('vidoff').innerHTML = 'Stranger has no video'
  }
  otherUser = ou
})

socket.on('dc', (msg) => {
  console.log(msg)
  document.getElementById('remote-video').srcObject = undefined
  joined = false
  serverMsg('User has disconnected, click "New Room"')
  document.getElementById('vidoff').innerHTML = ''
})

socket.on('other peer', (pid) => {
  //joiner
  console.log('pid ' + pid)
  otherPeerID = pid
})

function serverMsg(msg) {
  let item = document.createElement('li')
  item.innerHTML = "<h4 id='server'>Server: </h4>" + msg
  messages.appendChild(item)
  theMessages.scrollTo(0, theMessages.scrollHeight)
}

function strangerMsg(msg) {
  let item = document.createElement('li')
  item.innerHTML = '<h4>Stranger: </h4>' + msg
  messages.appendChild(item)
  theMessages.scrollTo(0, theMessages.scrollHeight)
}

**Comment by Ayushpanditmoto** [comment]
Here is the source code if you can help in running remotevideo

https://github.com/Ayushpanditmoto/Flutter_Omegle/

**Comment by MuhammedKpln** [comment]
> Here is the source code if you can help in running remotevideo
> 
> https://github.com/Ayushpanditmoto/Flutter_Omegle/

You may have provided the wrong demo because i don't see any call initiated from this client. Second example does not really belong here? Are you trying to connect from a browser client to a mobile? Can i also get a example from the browser client

**Comment by Ayushpanditmoto** [comment]
See this is my backend Code hosted in heroku 
used in this project
https://panditomegle.herokuapp.com/

actually I am using Socket.io as a backend and hosted in heroku 
only things left to write logic in flutter omegle clone app

i m trying to use flutter webrtc socket and peer js alternative i.e, peerdart 
this is my backend code but can u fix the flutter omegle clone source code as  i have wasted lot of time to build this project


![code](https://user-images.githubusercontent.com/31253617/197568681-37617c68-14e2-4171-9e78-e13c31fa3d95.png)

**Comment by MuhammedKpln** [comment]
Released a new [version(0.4.0-beta.3)](https://pub.dev/packages/peerdart/versions/0.4.0-beta.3), it should be fixed.

**Comment by Ayushpanditmoto** [comment]
Thanks for this source code
